version: '3'
services:
  mydatabase:
    image: mongo:latest
    container_name: "mydatabase_NOSQL_MONGODB"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=school-database
      - MONGO_DATABASE=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@127.0.0.1:27017/$MONGO_INITDB_DATABASE?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  