# flutter build apk --release --target-platform android-arm,android-arm64,android-x64 --split-per-abi
name: air_quality_system
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # state management
  stacked: ^1.7.1
  stacked_hooks: 0.1.1+3
  # navigation
  auto_route:
  stacked_services: ^0.4.3
  curved_navigation_bar: ^0.3.3

  # inversion of control
  get_it:
  injectable:

  cloud_firestore: ^0.13.7
  firebase_auth: 
  fluttertoast: ^3.1.3
  provider: ^4.0.3
  flutter_map: ^0.10.1
  geolocator: ^5.2.1
  location_permissions: ^3.0.0+1
  android_intent: ^0.3.7+2
  udp: ^3.0.3
  material_design_icons_flutter:
  get_ip: ^0.4.0
  # progress_hud: ^1.1.0

  # weather
  queries: "^0.0.15"
  intl: ^0.16.1
  http:
  flutter_sparkline: 
  country_pickers: ^1.1.0
  font_awesome_flutter: ^8.4.0
  feature_discovery: ^0.12.0+2
  liquid_pull_to_refresh: ^2.0.0
  shared_preferences: ^0.5.8
  connectivity: ^0.4.9

  # showcaseview: ^0.1.5
  # pull_to_refresh: ^1.6.0
  # rounded_loading_button: ^1.0.0
  # ping_discover_network: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:

    # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/img/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
